### ISSUE TITLE
No hover animations for buttons on details page

### ISSUE THREAD

**Issue by DaKheera47** [lscambo13/ElegantFin#7]
There's no hover animation for these buttons, which feels off

![image](https://github.com/user-attachments/assets/d03188a5-13d4-4fa1-b168-d5ff658f4f2a)

**Comment by lscambo13** [comment]
It should be fixed in the latest version (v24.12.03). 

You may need to hard refresh the page to make sure that the latest theme is pulled. To make sure that you are using the latest version of ElegantFin, check the version number at the bottom in the Dashboard screen.

Please check and report.

60c1651b42022ef189c2aad5e6ce1b35a4689c20
